sij_core:
    resource: "@SijCoreBundle/Controller/"
    type:     annotation
    prefix:   /

sij_user:
    resource: "@SijUserBundle/Controller/"
    type:     annotation
    prefix:   /

sij_pdf:
    resource: "@SijPdfBundle/Controller/"
    type:     annotation
    prefix:   /reporting