parameters:
#    sij_post.example.class: Sij\PostBundle\Example

services:
#    sij_post.example:
#        class: %sij_post.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
